[tox]
isolated_build = true
envlist = ruff-lint, ruff, py{310,311,312,313,314}
skip_missing_interpreters = true

[testenv]
description = Run the test suite with coverage
deps =
    pytest
    pytest-cov
commands = pytest --cov=nhs_number --cov-branch --cov-fail-under=100

[testenv:ruff-lint]
description = Lint code with Ruff
skip_install = true
deps = ruff
commands = ruff check .

[testenv:ruff]
description = Check code formatting with Ruff
skip_install = true
deps = ruff
commands = ruff format --check .