# .github/workflows/pypi-publish.yml
# This workflow will build the Python project, and publish it to pypi.org

name: Publish library to pypi.org on pushes to `main` branch

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build the distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.13

      - run: |
          pip install poetry
          poetry build

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist
          path: ./dist

  # this is a separate job so that the build job does not have access to the PyPI token
  pypi-test-publish:
    needs: ["build"]
    environment: release

    name: Upload from main branch to pypi.org
    runs-on: ubuntu-latest

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download package distributions from build job
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
